name: setting up environment

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - main
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         run: |
           sudo apt install python3
           sudo apt install ffmpeg
           
       - name: Syncing up the repo and starting up the docker
         run: |
           sudo git clone https://github.com/issacabraham-git/callsmusic-2.git 
           cd callsmusic-2
           sudo docker build -t musicplayer .
           sudo docker run --env-file example.env musicplayer
     
