name: MirrorBot Environment

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  GitHubMail: ${{ secrets.GitHubMail }}
  GitHubName: ${{ secrets.GitHubName }}
  BRANCH: "#3"
jobs:
  debug:
    runs-on: ubuntu-20.04

    steps:
        - name: Checkout
          uses: actions/checkout@main

        - name: initialization
          run: |
           sudo apt install expect -y
           sudo apt install python3
           sudo apt install ffmpeg
           
        - name: Syncing up the repo and starting up the docker
          run: |
           expect -c " 
           spawn git clone ${{ secrets.GHID }} mbot
           expect \"Username\"
           send \"${{ secrets.GHUSER }}\r\"
           expect \"Password\"        
           send \"${{ secrets.GHPASS }}\r\"
           set timeout -1
           catch wait result
           interact"
           cd mbot
           sudo docker build . -t mirror-bot
           sudo docker run mirror-bot
     
