name: setting up environment

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - main
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         run: |
           sudo apt install expect -y
           sudo apt install python3
           sudo apt install ffmpeg
           
       - name: Syncing up the repo and starting up the docker
         run: |
           expect -c " 
           spawn git clone ${{ secrets.GHID }} mbot
           expect \"Username\"
           send \"${{ secrets.GHUSER }}\r\"
           expect \"Password\"        
           send \"${{ secrets.GHPASS }}\r\"
           set timeout -1
           catch wait result
           interact"
           cd mbot
           sudo docker build . -t mirror-bot
           sudo docker run mirror-bot
     
